version: '2'

services:
  wordpress:
    stdin_open: true
    tty: true
    build:
      context: .
      dockerfile: ./compose/local/wordpress/Dockerfile
    depends_on:
      - mariadb
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: mariadb
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DEBUG: 1
    volumes:
      - ./wp-root:/var/www/html/
      - ./themes/nossas-dcp:/var/www/html/wp-content/themes/nossas-dcp
      - ./plugins/dcp-plugin/:/var/www/html/wp-content/plugins/dcp-plugin/
      - ./plugins/hacklab-dev-utils:/var/www/html/wp-content/plugins/hacklab-dev-utils
      - ./compose/local/wordpress/htaccess:/var/www/html/.htaccess
      - ./compose/local/wordpress/php/extra.ini:/usr/local/etc/php/conf.d/extra.ini
    networks:
      - wordpress-bot
      - interna

  watcher:
    build:
      context: .
      dockerfile: ./compose/local/watcher/Dockerfile
    volumes:
      - ./themes/nossas-dcp:/app

  mariadb:
    image: mariadb:10.4
    volumes:
      - ./mariadb_data:/var/lib/mysql
      - ./compose/local/mariadb/data:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: therootpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - interna

volumes:
  mariadb_data:

networks:
  interna:
    driver: bridge
  wordpress-bot:
    external: true
