name: CI - Docker WordPress

on:
  push:
    branches:
      - main  # ou 'main', conforme o nome da sua branch principal
  pull_request:
    branches:
      - main  # ou 'main', conforme o nome da sua branch principal

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configuração do Docker
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Instalar Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Subir containers (teste de build)
        run: docker-compose up -d --build

      - name: Verificar containers em execução
        run: docker ps

      - name: Derrubar containers após o teste
        run: docker-compose down 
