name: CI - Docker WordPress

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configuração do Docker
        uses: docker/setup-buildx-action@v3
        with:
          version: latest

      - name: Instalar Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Subir containers (teste de build)
        run: docker-compose up -d --build

      - name: Verificar containers em execução e salvar log
        run: |
          docker ps > docker-ps.log
          docker-compose logs > docker-compose.log

      - name: Derrubar containers após o teste
        run: docker-compose down

      - name: Upload de logs como artefato
        uses: actions/upload-artifact@v4
        with:
          name: logs-docker
          path: |
            docker-ps.log
            docker-compose.log